---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ../data:/data
        user: "1000:1000"
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile.api
        depends_on:
            - redis-db
        environment:
            - REDIS-IP=redis-db
        image: lucalabardini/quant:1.0 #jthet/quant_stock_api:1.0.1
        ports:
            - 5000:5000
        volumes:
            - ./config.yaml:/config/config.yaml
    worker:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.wrk
        depends_on:
            - redis-db
        environment:
            - REDIS-IP=redis-db
        image: lucalabardini/qworker:1.0 #jthet/quant_stock_worker:1.0.1